# Generated by Django 2.2.13 on 2022-02-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(choices=[('black', 'BLACK'), ('brown', 'BROWN'), ('blonde', 'BLONDE'), ('red', 'RED'), ('white', 'WHITE'), ('bald', 'BALD')], max_length=32),
        ),
    ]
